apiVersion: apps/v1
kind: Deployment
metadata:
  name: manytimesjob-controller
spec:
  selector:
    matchLabels:
      app: manytimesjob
      version: latest
  replicas: 1
  template:
    metadata:
      labels:
        app: manytimesjob
        version: latest
    spec:
      serviceAccountName: default
      containers:
      - name: controller
        image: docker.io/kanatakita/manytimesjob:latest
        imagePullPolicy: IfNotPresent

