# permissions to do viewer manytimesjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manytimesjob-viewer-role
rules:
- apiGroups:
  - batch.kanatakita.com
  resources:
  - manytimesjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.kanatakita.com
  resources:
  - manytimesjobs/status
  verbs:
  - get
